### ISSUE TITLE
setup in branch:problems with cuda

### ISSUE THREAD

**Issue by BenjaminBo** [ethnhe/PVN3D#44]
Hi,
after switching to Ubuntu 18.4 and following the steps from the branch (https://github.com/ethnhe/PVN3D/tree/pytorch-1.5) I get the following Error after running ```python3 setup.py build_ext```:
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=47 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    'build_ext': BuildExtension
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/benjamin/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/benjamin/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 396, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 372, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1400, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability()
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/torch/cuda/__init__.py", line 309, in get_device_capability
    prop = get_device_properties(device)
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/torch/cuda/__init__.py", line 314, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/benjamin/anaconda3/envs/pvn3d_b/lib/python3.6/site-packages/torch/cuda/__init__.py", line 190, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:47

```

The message ```no CUDA-capable device is detected``` surprises me since I did follow the steps for the CUDA installatio.

**Comment by BenjaminBo** [comment]
I'm closing this issue because the problem seems to be that I am using Ubuntu - and therefore also nvidia and cuda 10.1 - with VirtualBox in a VM, which doesnt work. nvidia doesn't seem to have access to my GPU through the VM.
