### ISSUE TITLE
The trining error on the dataset of linemod

### ISSUE THREAD

**Issue by tsuchidashinya** [ethnhe/PVN3D#61]
train_dataset_size:  79731
cls_id in lm_dataset.py 1
val_dataset_size:  1050
loading pretrained mdl.
Traceback (most recent call last):
  File "/root/anaconda3/envs/PV3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/PV3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/dl-box/472a1568-af4c-4f0d-9c26-2f1d5af5a772/PVN/PVN3D/pvn3d/train/train_linemod_pvn3d.py", line 490, in <module>
    mode = 'triangular'
  File "/media/dl-box/472a1568-af4c-4f0d-9c26-2f1d5af5a772/PVN/PVN3D/pvn3d/lib/utils/warmup_scheduler/scheduler.py", line 240, in __init__
    super().__init__(optimizer)
  File "/root/anaconda3/envs/PV3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 77, in __init__
    self.step()
TypeError: step() missing 1 required positional argument: 'step'

Why it need to reload the pretrainning model?

**Comment by ethnhe** [comment]
As the error says, it's about the lr_scheduler, which changed in some versions after pytorch 1.0. You can try the [pytorch-1.5](https://github.com/ethnhe/PVN3D/tree/pytorch-1.5) branch.
